### ISSUE TITLE
How does one change the value of the UI elements?

### ISSUE THREAD

**Issue by joshuaalm** [msawired/OPC#1]
I created a rotation cypher encoding/decoding sketch, and today I found this project library had been added to OpenProcessing, so I added the UI elements for inputting the text and a slider for changing the rotation.  However, my initial sketch used the keyboard up/down keys in order to change the rotation, and I would like to update the slider value to reflect when that input is used to change the rotation.

Sketch here: https://openprocessing.org/sketch/1527550

**Comment by msawired** [comment]
That's a great feedback! I made the variables reactive and added support for automatically updating the components when variables are adjusted within the code. Should work if you update the library version to 0.2.1. I tried it on your sketch, and worked like a charm!

**Comment by joshuaalm** [comment]
That’s awesome!  I’m glad it helped!  I will look forward to OpenProcessing
updating the library on their site.

**Comment by msawired** [comment]
It is already updated. You can click on the version number next to the library, and select v0.2.1.
