### ISSUE TITLE
Buttons in darkmode are illegible

### ISSUE THREAD

**Issue by esperanc** [msawired/OPC#11]
If a sketch is started whilst in dark mode, the OPC buttons become illegible, since the text color is set to white and so is the button's background. Here's an example

![Screenshot 2024-11-02 at 13 47 25](https://github.com/user-attachments/assets/953b630b-9ac5-4074-a6c4-78e5c8a441c1)

**Comment by msawired** [comment]
Thank you for reporting. I fixed this issue. Let me know if you still experience it!
