### ISSUE TITLE
Feature request: Labels / descriptions

### ISSUE THREAD

**Issue by chubas** [msawired/OPC#6]
Sometimes is useful to add a different label other than the variable name, or even add a text above the variable name, to provide more information to the viewer of the options. This would not change existing functionality and the internal variable name is kept. 
* Label: as an alternative text in place of the variable name
* Description: as a longer text that can be placed above the control

There are several ways this could be achieved, as to modify as little as possible existing API:

* Passed as an extra parameter to the existing ones, e.g.
```
OPC.slider('someValue', 1, 0, 10, 1, 'Some description')
```

* Passed as an options extra parameter, which also gives some flexibility to further customize controls in the future, e.g. 
```
OPC.slider('someValue', 1, 0, 10, 1, {
  label: 'Some label',
  description: 'Some long description'
}
```

* Associated using the variable name, e.g.
```
OPC.slider('someValue', ...);
OPC.label('someValue', 'some label');
OPC.description('someValue', 'some long description')
```

* Willing to change the internal API a bit, chaining the call, e.g.
```
OPC.slider('someValue', ...).label('some label').description('some long description')
```

I would like to hear your thoughts if this is a useful change, I'm willing to implement it

**Comment by msawired** [comment]
I received that feedback before, so yes, I think it makes sense to explore a solution for this. I like both the options (a json object) and method chaining options. I think I am more inclined to passing a single json object for all the parameters, including the default and extra params.
Such as:
```
OPC.slider({
  variable: 'someValue',
  default: 1,
  min: 0,
  max: 10,
  step: 1,
  label: 'Some label',
  description: 'Some long description',
  //... this would also support for any future additions.
});
```
This would also make things easier to handle in the code. We can look if first parameter is string or an object. If object, then reads all the data from the given object. If string, reads the few allowed parameters from the function arguments directly (as it does now).
What do you think?

**Comment by chubas** [comment]
I like that idea! My intention is to not change the API so I didn't want to suggest a parameter object, but if a check can be made about the type of parameter without breaking existing code that would be awesome, as I would assume this version is going to be updated on the OpenProcessing available libraries. We can assume that all current uses of this is on the first form `OPC.control(string, ...params)`. And I do like the extensibility that it provides.

I'll work on a version of this during the week, and will link it externally for testing with OP existing sketches to validate

**Comment by msawired** [comment]
Correct, all current users wouldn't be effected by this change. We would release this as a major version anyways, so anyone who would like to upgrade would have to change the version number manually anyways. I wouldn't worry about that.
For testing, I would need to make updates on OpenProcessing as well to support "label" and "description", so let me know once you have a new branch with updates, and I will work on adding support for label and description on the website component.
[Putting this as a note here]: it is also in my to-do list that, this library should include a simple client version, similar to the one on OP, so that any changes can be tested easily. This way, this library would also become fully independent.

**Comment by chubas** [comment]
Funny that you mention it, as in order to develop this change I kinda needed a simple client version, ended up building it myself :)
![opc](https://github.com/msawired/OPC/assets/47891/46f6d9cb-0a68-495e-963a-13ac9776ec28)
May lack some features on the OP one but is mostly functional (albeit still ugly) atm. Got sidetracked by this, I'll share once I polish it a bit - then I'll test the label / description changes on it 😅

**Comment by msawired** [comment]
Actually, your vanilla JS client UI is perfect! I was thinking developing a base client library that converts OPC data into native form input elements and yours seem to exactly do this. So, skinning this per use case would be up to the user.  I would love to add this to the OPC library.
So, maybe we can create two client folders: "client/native" and "client/vue". Any can add their implementation in the future if they like.

**Comment by msawired** [comment]
One component that doesn't have a native version is "color palette", and in the native version we can convert this as Select input.

**Comment by chubas** [comment]
I guess this one is solved with https://github.com/msawired/OPC/pull/7, I'll close the feature request
