### ISSUE TITLE
The step parameter in slider doesn't work

### ISSUE THREAD

**Issue by TotallyReal** [msawired/OPC#9]
In the slider generation, the step parameter doesn't work. The line 
`step = variableNameOrConfig ?? step;`
should probably be 
`step = variableNameOrConfig.step ?? step;`

**Comment by msawired** [comment]
Hello, thank you for reporting this. Yes, I can confirm the bug, and I fixed it on f4f0fb4fc5f5bf14e28332f8ed772e57e7cc0213  . Should be available on OP with v0.4.1
